# Generated by Django 5.0.7 on 2024-08-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_price', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveBigIntegerField()),
                ('total_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', to='stock.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
