# Generated by Django 5.0.7 on 2024-08-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='total_price',
            new_name='added_quantity',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='remaining_quantity',
        ),
        migrations.AddField(
            model_name='stock',
            name='added_quantity_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='initial_quantity',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='initial_quantity_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='remaining_quantity_total_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
