# Generated by Django 5.0.7 on 2024-08-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_total_price_stock_added_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='initial_quantity',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='remaining_quantity',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
