# Generated by Django 5.0.7 on 2024-08-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafecms',
            old_name='email_3',
            new_name='cafe_email',
        ),
        migrations.AlterField(
            model_name='cafecms',
            name='email_1',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
