# Generated by Django 5.0.7 on 2024-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_email_3_cafecms_cafe_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafecms',
            name='pana_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
