# Generated by Django 5.0.7 on 2024-08-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('discount_rate', models.PositiveBigIntegerField(blank=True, null=True)),
                ('grand_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('bill_created', models.DateField(auto_now_add=True)),
                ('bill_time', models.TimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
            ],
        ),
    ]
