# Generated by Django 5.0.7 on 2024-08-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tabel_number',
            new_name='table_number',
        ),
    ]
