# Generated by Django 5.0.7 on 2024-08-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_tabel_number_order_table_number'),
        ('stock', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='table', to='stock.table'),
        ),
    ]
